DROP DATABASE IF EXISTS DBEXERCICIO02;

CREATE DATABASE DBEXERCICIO02;

USE DBEXERCICIO02;

CREATE TABLE NOTA (
	ID_NOTA INT NOT NULL auto_increment,
    ALUNO VARCHAR(100) NOT NULL,
    NOTA_1B NUMERIC(4,2),
    NOTA_2B NUMERIC(4,2),
    NOTA_3B NUMERIC(4,2),
    NOTA_4B NUMERIC(4,2),
    MEDIA NUMERIC(4,2),
    RESULTADO varchar(10),
    primary key(ID_NOTA)
);