-- Apagando o Banco de Dados caso exista
DROP DATABASE IF EXISTS DBEXERCICIO01;

-- CRIANDO O BANCO DE DADOS:
CREATE DATABASE DBEXERCICIO01;

-- CONECTANDO AO BANCO DE DADOS:
USE DBEXERCICIO01;

-- CRIANDO AS TABELAS:
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL auto_increment,
    CPF char(11),
    NOME varchar(120) NOT NULL,
    IDADE INT,
    primary key(IDALUNO)
);