DROP DATABASE IF EXISTS DBEXERCICIO03;

CREATE DATABASE DBEXERCICIO03;

USE DBEXERCICIO03;

CREATE TABLE AVALIACAO (
	ID_AVALIACAO INT NOT NULL auto_increment,
    NOME VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(45),
    IDADE INT,
    NOTA decimal(3,1) NOT NULL,
    primary key(ID_AVALIACAO)
);