-- DESATIVANDO O MODO SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO15;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO15;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO15;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE CURSO (
	IDCURSO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , CARGA_HORARIA INT NOT NULL
    , PRIMARY KEY (IDCURSO)
);

CREATE TABLE MATRICULA (
	IDMATRICULA INT NOT NULL AUTO_INCREMENT
    , DT_MATRICULA DATE NOT NULL
    , IDALUNO INT NOT NULL
    , IDCURSO INT NOT NULL
    , PRIMARY KEY (IDMATRICULA)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
    , FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO)
);

INSERT INTO ALUNO (NOME, EMAIL) VALUES
('LUCAS MENDES', 'LUCAS@EMAIL.COM'),
('JULIA MARTINS','JULIA@EMAIL.COM'),
('PEDRO SOUZA', 'PEDRO@EMAIL.COM');

INSERT INTO CURSO (NOME, CARGA_HORARIA) VALUES
('ITRODUCAO AO PYTHON', 40),
('BANCO DE DADOS RELACIONAL', 60),
('ESTATISTICA PARA DADOS', 60);

INSERT INTO MATRICULA (IDALUNO, IDCURSO, DT_MATRICULA)VALUES
(1, 1, '2025-03-01'),
(2, 1, '2025-03-05'),
(1, 2, '2025-03-10'),
(3, 3, '2025-04-01'),
(2, 3, '2025-04-02');


