-- DESATIVANDO O MODO SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO14;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO14;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO14;

-- CRIANDO AS TABELAS
CREATE TABLE PROFESSOR (
	IDPROFESSOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , DISCIPLINA VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDPROFESSOR)
);

CREATE TABLE TURMA (
	IDTURMA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , ANO INT NOT NULL
    , IDPROFESSOR INT NOT NULL
    , PRIMARY KEY (IDTURMA)
    , FOREIGN KEY (IDPROFESSOR) 
		REFERENCES PROFESSOR(IDPROFESSOR)
);

INSERT INTO PROFESSOR (NOME, DISCIPLINA) VALUES
('MARIANA COSTA', 'MATEMATICA'),
('FELIPE OLIVEIRA','HISTORIA'),
('RENATA ALMEIDA', 'QUIMICA');

INSERT INTO TURMA (NOME, ANO, IDPROFESSOR)VALUES
('1A', 2025, 1),
('2B', 2025, 2),
('3C', 2025, 1),
('1B', 2025, 3),
('2A', 2025, 1);


