-- DESABILITANDO O MODE SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIOO16;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIOO16;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIOO16;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TURMA VARCHAR(50) NOT NULL
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL AUTO_INCREMENT
    , TITULO VARCHAR(120) NOT NULL
    , AUTOR VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDLIVRO)
);

CREATE TABLE EMPRESTIMO (
	IDEMPRESTIMO INT NOT NULL AUTO_INCREMENT
    , IDALUNO INT NOT NULL
    , IDLIVRO INT NOT NULL
    , DT_EMPRESTIMO DATE NOT NULL
    , DT_DEVOLUCAO DATE
    , PRIMARY KEY (IDEMPRESTIMO)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
    , FOREIGN KEY (IDLIVRO) REFERENCES LIVRO(IDLIVRO)
);

INSERT INTO ALUNO (NOME, TURMA)VALUES
('BEATRIZ LIMA', '2A')
, ('RAFAEL MONTEIRO', '1B')
, ('CAMILA TORRES', '3C');

INSERT INTO LIVRO (TITULO, AUTOR) VALUES
('DOM CASMURRO', 'MACHADO DE ASSIS')
, ('O PEQUENO PRINCIPE', 'ANTOINE DE SAINT-EXUPERY')
, ('CAPITAES DA AREA', 'JORGE AMANDO');

INSERT INTO EMPRESTIMO (IDALUNO, IDLIVRO, DT_EMPRESTIMO, DT_DEVOLUCAO) VALUES
(1, 1, '2025-04-01', '2025-04-10')
, (2, 2, '2025-04-03', '2025-04-15')
, (1, 3, '2025-04-05', NULL)
, (3, 1, '2025-04-07', NULL);