-- DESABILITANDO O MODE SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIOO17;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIOO17;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIOO17;

-- CRIANDO AS TABELAS
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE CATEGORIA (
	IDCATEGORIA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , IDCATEGORIA INT NOT NULL
    , NOME VARCHAR(120) NOT NULL
    , PRECO_UNITARIO DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDPRODUTO)
    , FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
);

CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , DT_PEDIDO DATE NOT NULL
    , PRIMARY KEY (IDPEDIDO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
	IDPEDIDO INT NOT NULL AUTO_INCREMENT
    , IDPRODUTO INT NOT NULL
    , QTDE INT NOT NULL
    , PRECO_UNITARIO DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDPEDIDO, IDPRODUTO)
    , FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

INSERT INTO CLIENTE (NOME, TELEFONE)VALUES
('MARIA OLIVEIRA', '11999998888')
, ('JOAO DA SILVA', '11988887777');

INSERT INTO CATEGORIA (NOME) VALUES
('BEBIDAS')
, ('PRATOS')
, ('SOBREMESAS');

INSERT INTO PRODUTO (IDCATEGORIA, NOME, PRECO_UNITARIO) VALUES
(1, 'COCA-LOCA LATA', 5.00)
, (2, 'HAMBURGUER CLASSICO', 18.00)
, (3, 'PUDIM', 8.00)
, (1, 'SUCO NATURAL', 6.50);

INSERT INTO PEDIDO (IDCLIENTE, DT_PEDIDO) VALUES
(1, '2025-04-20')
, (2, '2025-04-21');

INSERT INTO ITEM_PEDIDO (IDPEDIDO, IDPRODUTO, QTDE, PRECO_UNITARIO) VALUES
(1, 2, 2, 18.00)
, (1, 1, 1, 5.00)
, (2, 3, 1, 8.00)
, (2, 4, 2, 6.50);