-- SELECIONANDO O BANCO DE DADOS 14.
USE DBEXERCICIO14;

-- ############################
-- LISTAR TODOS OS PROFESSORES.
SELECT * FROM PROFESSOR;


-- #############################
-- LISTAR O NOME SOMENTE DO PROFESSOR DE MATEMÁTICA.
SELECT
	NOME
FROM
	PROFESSOR
WHERE
	DISCIPLINA = 'MATEMATICA';


-- #############################
-- LISTAR O NOME E DISCIPLINA DO PROFESSOR DA TURMA 2A.
SELECT
	PROFESSOR.NOME,
    PROFESSOR.DISCIPLINA,
    TURMA.NOME
FROM
	PROFESSOR
    inner join TURMA ON
    PROFESSOR.IDPROFESSOR = TURMA.IDPROFESSOR
WHERE
	TURMA.NOME = '2A';


-- #############################
-- LISTAR QUASE TODOS OS DADOS.
SELECT
	TURMA.IDTURMA,
    TURMA.NOME AS NOME_TURMA,
    PROFESSOR.IDPROFESSOR,
    PROFESSOR.NOME AS NOME_PROFESSOR,
    PROFESSOR.DISCIPLINA
FROM
	PROFESSOR
    INNER JOIN TURMA ON
    PROFESSOR.IDPROFESSOR = TURMA.IDPROFESSOR;
    
    

-- #################################################################
-- CONECTANDO AO BANCO DE DADOS DO EXERCICIO 15.
-- LISTAR TODOS OS ALUNOS CADASTRADOS.
SELECT * FROM ALUNO;

-- LISTAR TODOS OS CRUSOS CADASTRADOS.
SELECT * FROM CURSO;

-- LISTAR A DISCIPLICA DO LUCAS
SELECT
	ALUNO.NOME,
    ALUNO.EMAIL,
    CURSO.NOME
FROM
	ALUNO
    INNER JOIN MATRICULA ON
    ALUNO.IDALUNO = MATRICULA.IDALUNO
    INNER JOIN CURSO ON
    CURSO.IDCURSO = MATRICULA.IDCURSO
WHERE
	ALUNO.NOME LIKE 'LUCAS%';
    
    
-- SELECIONAR TODOS OS CAMPOS
SELECT
	MATRICULA.IDMATRICULA,
    MATRICULA.DT_MATRICULA,
    ALUNO.IDALUNO,
    ALUNO.NOME,
    ALUNO.EMAIL,
    CURSO.IDCURSO,
    CURSO.NOME,
    CURSO.CARGA_HORARIA
FROM
	ALUNO
    INNER JOIN MATRICULA ON
    MATRICULA.IDALUNO = ALUNO.IDALUNO
    INNER JOIN CURSO ON 
    CURSO.IDCURSO = MATRICULA.IDCURSO;
    
-- LISTAR TODOS OS ALUNOS NO CURSO DE BANCO DE DADOS
SELECT
	ALUNO.NOME,
    ALUNO.EMAIL
FROM
	ALUNO
    INNER JOIN MATRICULA ON
    MATRICULA.IDALUNO = ALUNO.IDALUNO
    INNER JOIN CURSO ON
    CURSO.IDCURSO = MATRICULA.IDCURSO
WHERE
	CURSO.NOME = 'BANCO DE DADOS RELACIONAL';
    
-- #################################################################
-- CONECTANDO AO BANCO DE DADOS DO EXERCICIO 16.
-- LISTAR TODOS OS ALUNOS CADASTRADOS.
SELECT * FROM ALUNO;

-- Listar todos os livros cadastrados
SELECT * FROM LIVRO;

-- Listar o nome do aluno, o nome do livros a data do empréstimo de todos os alunos que não tem data de devolução
SELECT
	ALUNO.NOME AS NOME_ALUNO,
    LIVRO.TITULO,
    EMPRESTIMO.DT_EMPRESTIMO
FROM
	ALUNO
    INNER JOIN EMPRESTIMO ON
    EMPRESTIMO.IDALUNO = ALUNO.IDALUNO
    INNER JOIN LIVRO ON
    LIVRO.IDLIVRO = EMPRESTIMO.IDLIVRO
WHERE
	EMPRESTIMO.DT_DEVOLUCAO IS NULL;


-- #################################################################
-- CONECTANDO AO BANCO DE DADOS DO EXERCICIO 17.
-- Listar todos os cliente cadastrados
SELECT * FROM CLIENTE;

-- Listar todos os produtos cadastrados, mostre também a categoria do produto
SELECT
	PRODUTO.NOME,
    CATEGORIA.NOME
FROM
	PRODUTO
    INNER JOIN CATEGORIA ON
    CATEGORIA.IDCATEGORIA = PRODUTO.IDCATEGORIA
WHERE
	CATEGORIA.IDCATEGORIA = PRODUTO.IDCATEGORIA;