SET SQL_SAFE_UPDATES = 0;
-- DROP DATABASE IF EXISTS DBESTACIONAMENTO;
CREATE DATABASE DBESTACIONAMENTO;

USE DBESTACIONAMENTO;

CREATE TABLE PRECO_HORA(
	ID_PRECO INT NOT NULL primary key auto_increment,
    DESCRICAO varchar(50),
    VALOR_HORA decimal(10,2)
);

CREATE TABLE VEICULO (
	ID_VEICULO INT NOT NULL PRIMARY KEY auto_increment,
	PLACA VARCHAR(10),
    ENTRADA DATETIME NOT NULL,
    SAIDA DATETIME,
    TEMPO_PERMANENCIA DECIMAL(10,2),
    TOTAL_A_PAGAR DECIMAL(10,2),
    PRECO_HORA_ID INT,
    foreign key (PRECO_HORA_ID) references PRECO_HORA(ID_PRECO)
);


SELECT * FROM VEICULO; 

UPDATE VEICULO SET ENTRADA = DATE_ADD(NOW(), INTERVAL -25 MINUTE);

SELECT * FROM PRECO_HORA;
INSERT INTO PRECO_HORA (descricao, valor_hora) VALUES ('Valor do estacionamento', 7.00);

SELECT
	PLACA,
    ENTRADA,
    SAIDA,
    VALOR_HORA
FROM
	 PRECO_HORA INNER JOIN VEICULO ON
     PRECO_HORA.ID_PRECO = 1;

-- Testando intervalo de tempo.
SELECT
	PLACA
    , ENTRADA
	, SAIDA
    , TEMPO
    , HOUR(TEMPO) + (MINUTE(TEMPO) / 60) + (SECOND(TEMPO) / 360) AS TEMPO_HORA
    , (HOUR(TEMPO) * 60) + MINUTE(TEMPO) + (SECOND(TEMPO) / 60) AS TEMPO_MINUTO
FROM (
	SELECT
		PLACA
        , ENTRADA
		, SAIDA
		, TIMEDIFF(SAIDA, ENTRADA) AS TEMPO
	FROM
		VEICULO
	WHERE
		PLACA = '123'
) as sub