SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBESTACIONAMENTO;
CREATE DATABASE DBESTACIONAMENTO;

USE DBESTACIONAMENTO;

CREATE TABLE PRECO_HORA(
	ID_PRECO INT NOT NULL primary key auto_increment,
    DESCRICAO varchar(50),
    VALOR_HORA decimal(10,2)
);

CREATE TABLE VEICULO (
	ID_VEICULO INT NOT NULL PRIMARY KEY auto_increment,
	PLACA VARCHAR(10),
    ENTRADA DATETIME NOT NULL,
    SAIDA DATETIME,
    PRECO_HORA_ID INT,
    foreign key (PRECO_HORA_ID) references PRECO_HORA(ID_PRECO)
);

SELECT * FROM VEICULO;