SET SQL_SAFE_UPDATES = 0;
#DROP DATABASE IF EXISTS DBESTACIONAMENTO;
CREATE DATABASE DBESTACIONAMENTO;

USE DBESTACIONAMENTO;

CREATE TABLE VEICULO (
	#ID_CLIENTE INT NOT NULL PRIMARY KEY auto_increment,
	PLACA VARCHAR(10),
    ENTRADA DATETIME,
    SAIDA DATETIME
);

-- INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(1, 'FINANCEIRO');

SELECT * FROM VEICULO;