SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS SENAC;
CREATE DATABASE SENAC;

USE SENAC;

CREATE TABLE CLIENTE (
	ID_CLIENTE INT NOT NULL PRIMARY KEY auto_increment,
	NOME VARCHAR(100),
    IDADE INT,
    SEXO char(1),
    DT_NASCIMENTO DATE
);

-- INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(1, 'FINANCEIRO');

SELECT * FROM CLIENTE;