SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBEMPRESA;
CREATE DATABASE DBEMPRESA;

USE DBEMPRESA;

CREATE TABLE DEPARTAMENTO (
	IDDEPARTAMENTO INT NOT NULL PRIMARY KEY auto_increment,
	NOME VARCHAR(100)
);

INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(1, 'FINANCEIRO');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(2, 'COBRANÇA');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(3, 'CONTABILIDADE');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(4, 'AUDITORIA');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(5, 'LOGISTICA');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(6, 'PRODUÇÃO');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(7, 'OPERAÇÕES');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(8, 'RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME)VALUES(9, 'TI');

CREATE TABLE FUNCAO (
	IDFUNCAO INT NOT NULL PRIMARY KEY auto_increment,
	NOME VARCHAR(100)
);

INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(1, 'ANALISTA ADMINISTRATIVO');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(2, 'ANALISTA FINANCEIRO');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(3, 'ANALISTA DE SISITEMAS');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(4, 'ANALISTA DE RECURSOS HUMANOS');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(5, 'ASSISTENTE DE MANUTENÇÃO');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(6, 'ASSISTENTE ADMINISTRATIVO');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(7, 'SECRETÁRIA');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(8, 'AUXILIAR ADMINISTRATIVO');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(9, 'AUXILIAR DE PRODUÇÃO');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(10, 'OPERADOR');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(11, 'ENCARREGADO');
INSERT INTO FUNCAO (IDFUNCAO, NOME)VALUES(12, 'PROGRAMADOR');

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL PRIMARY KEY auto_increment,
	IDDEPARTAMENTO INT NOT NULL,
	IDFUNCAO INT NOT NULL,
	NOME VARCHAR(100),
	SEXO CHAR(1),
	IDADE INT,
	DTADMISSAO DATETIME NOT NULL,
	DTDEMISSAO DATETIME,
	SALARIO NUMERIC(9,2),
	CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO (IDDEPARTAMENTO),
	CONSTRAINT FK_FUNCIONARIO_FUNCAO FOREIGN KEY (IDFUNCAO) REFERENCES FUNCAO (IDFUNCAO) 
);

INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(1,  2, 'Robert Pers'		, 'M', 19, '2012-01-16 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(1,  8, 'Roberto Garcam'	, 'M', 25, '2011-08-22 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(1,  8, 'Guilherme Maril'	, 'M', 25, '2012-02-17 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(1,  7, 'Aline Cristina'	, 'F', 19, '2000-08-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(2,  1, 'Jerônimo DalaSi'	, 'M', 26, '2012-01-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(2,  6, 'Thiago Ciello'		, 'M', 29, '2011-11-17 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(2,  7, 'Aline Batista'		, 'F', 19, '2001-08-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(3,  1, 'Lucas Logrini'		, 'M', 28, '2012-07-22 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(3,  6, 'Lucas Mellva'		, 'M', 29, '2012-08-18 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(3,  7, 'Beatriz AlVinO'	, 'F', 22, '2004-10-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(4,  1, 'Roberto Adez'		, 'M', 26, '2012-08-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(4,  6, 'Pedro Siues'		, 'M', 19, '2011-01-28 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(4,  6, 'Nathan Sendil'		, 'M', 25, '2012-10-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(4,  7, 'Gabriela Cristina'	, 'F', 30, '2012-05-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(5,  1, 'Paulo Cerasa'		, 'M', 22, '2002-08-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(5,  6, 'Lucas Olivio'		, 'M', 28, '2012-12-22 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(5,  6, 'João Viwerz'		, 'M', 19, '2011-08-13 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(5,  7, 'Gabrielle Alenade'	, 'F', 25, '2012-11-13 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(6,  5, 'Matheus kamp'		, 'M', 30, '2012-08-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(6,  9, 'Matheus Lorb'		, 'M', 26, '2001-04-22 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(6, 10, 'Rhuan Rorti'		, 'M', 28, '2012-02-13 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(6, 10, 'Paulo Heqt'		, 'M', 19, '2002-08-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(6,  7, 'Victoria Cuehler'	, 'F', 27, '2012-12-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(7,  6, 'João Saebr'		, 'M', 30, '2002-08-14 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(7, 11, 'Lucas Furil'		, 'M', 22, '2001-03-22 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(7, 10, 'Rhamon Rool'		, 'M', 31, '2012-07-14 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(7, 10, 'Matheus Moricensk'	, 'M', 19, '2002-08-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(8,  4, 'Rodrigo Livier'	, 'M', 22, '2012-03-16 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(8,  8, 'Guilherme Freder'	, 'M', 26, '2001-09-22 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(8,  8, 'Ricardo Rodess'	, 'M', 19, '2012-08-22 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(9,  3, 'Gabriel Aller'		, 'M', 27, '2010-05-12 14:00:00', 0000.00);
INSERT INTO FUNCIONARIO (IDDEPARTAMENTO, IDFUNCAO, NOME, SEXO, IDADE, DTADMISSAO, SALARIO)VALUES(9, 12, 'Breno BeieRosa'	, 'M', 19, '2012-08-26 14:00:00', 0000.00);

update funcionario set SALARIO = RAND() * 1000 * 2;
update funcionario set SALARIO =  SALARIO * 20 where SALARIO < 200;
update funcionario set SALARIO =  SALARIO * 10 where SALARIO < 100;
update funcionario set SALARIO =  SALARIO * 4 where SALARIO < 300;
update funcionario set SALARIO =  SALARIO * 2 where SALARIO < 700;


-- ############################################################################################
-- Resolução exercício
-- Questão 1.
/* Crie uma consulta SQL para listar o nome do funcionário, e o nome do 
departamento, de todos os funcionários que trabalham no departamento "financeiro"; 
*/
SELECT
	FUNCIONARIO.NOME AS NOME_FUNCIONÁRIO,
    DEPARTAMENTO.NOME AS NOME_DEPARTAMENTO
FROM
	DEPARTAMENTO
    INNER join FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO;
/*
WHERE
	DEPARTAMENTO.NOME = "FINANCEIRO";
*/
    

-- ############################################################################################
-- Questão 2.
SELECT 
	FUNCIONARIO.IDFUNCIONARIO,
    FUNCIONARIO.NOME,
    FUNCAO.NOME
FROM
	DEPARTAMENTO
    INNER JOIN FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO
    INNER JOIN FUNCAO ON
    FUNCIONARIO.IDFUNCIONARIO = FUNCAO.IDFUNCAO
WHERE 
	FUNCAO.NOME LIKE "%ASSISTENTE%";


-- ############################################################################################
-- Questão 3.
/*
	 Crie uma consulta SQL para listar o nome do funcionário, a data de admissão e 
o salário de todos os funcionários que recebem acima de R$ 1800; 
*/
SELECT
	FUNCIONARIO.NOME,
    FUNCIONARIO.DTADMISSAO,
    FUNCIONARIO.SALARIO
FROM
	DEPARTAMENTO
    INNER JOIN FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO
where 
	SALARIO > 1800;


-- ############################################################################################
-- questão 4.
/*
	 Crie uma consulta SQL para listar o nome e o salário de todos os funcionários 
do financeiro; 
*/
SELECT
	FUNCIONARIO.NOME,
    FUNCIONARIO.SALARIO
FROM 
	DEPARTAMENTO
    INNER JOIN FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO
WHERE
	DEPARTAMENTO.NOME = "CONTABILIDADE";
    

-- ############################################################################################
-- questão 5.
/*
	Crie uma consulta SQL para listar o código do funcionário, o nome do 
funcionário, o salário, o nome do departamento, e o nome da função, de todos os 
funcionários; 
*/
SELECT 
	FUNCIONARIO.IDFUNCIONARIO,
    FUNCIONARIO.NOME,
    FUNCIONARIO.SALARIO,
    DEPARTAMENTO.NOME AS DEPARTAMENTO,
    FUNCAO.NOME AS FUNÇÃO
FROM
	DEPARTAMENTO
    INNER JOIN FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO
    INNER JOIN FUNCAO ON
    FUNCIONARIO.IDFUNCIONARIO = FUNCAO.IDFUNCAO;
    

-- ############################################################################################
-- questão 6.
/*
	Crie uma consulta SQL para listar o maior salário, o menor salário, agrupado 
por sexo; 
*/

SELECT
	SEXO,
    MAX(SALARIO) AS SALARIO_MÁXIMO,
    MIN(SALARIO) AS MINIMO_SALARIO
FROM
	FUNCIONARIO
GROUP BY
	SEXO;
  
  
-- ############################################################################################
-- questão 7.
/*
Crie uma consulta SQL para listar a soma de todos os salario e a média salarial 
agrupado por departamento, liste também o código e o nome do departamento;
*/
SELECT
	SUM(SALARIO),
    avg(SALARIO),
    DEPARTAMENTO.IDDEPARTAMENTO,
    DEPARTAMENTO.NOME
FROM
	DEPARTAMENTO
    INNER JOIN FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO
GROUP BY
	DEPARTAMENTO.NOME,
    DEPARTAMENTO.IDDEPARTAMENTO;
    
    
-- ############################################################################################
-- questão 8.
/*
	 Crie uma consulta SQL para listar o salário de todos os funcionário com mais de 
1 ano de empresa, liste o nome do funcionário, o salário do funcionário e o nome da função 
exercida pelo funcionário;
*/
SELECT
	FUNCIONARIO.NOME,
	FUNCIONARIO.SALARIO,
    FUNCAO.NOME AS FUNCÃO
FROM
	DEPARTAMENTO
    INNER JOIN FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO
    INNER JOIN FUNCAO ON
    FUNCIONARIO.IDFUNCIONARIO = FUNCAO.IDFUNCAO
WHERE DATEDIFF(CURRENT_DATE(), DTADMISSAO) > 365;



-- ############################################################################################
-- questão 9.
/*
	Crie uma consulta SQL para listar a quantidade de funcionário por 
departamento, o resultado deve ser ordenado pelo nome do departamento;
*/
SELECT
	DEPARTAMENTO.NOME,
    COUNT(FUNCIONARIO.IDFUNCIONARIO) AS QTD_FUNCIONARIOS
FROM
	DEPARTAMENTO
    INNER JOIN FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO
GROUP BY
	DEPARTAMENTO.NOME
ORDER BY
	DEPARTAMENTO.NOME ASC;
    
    
-- ############################################################################################
-- questão 10.
/*
	Crie uma consulta SQL para listar a soma dos salários dos funcionários por 
função, listando também o maior e o menor salário
*/
SELECT
	FUNCAO.NOME,
    SUM(SALARIO) AS SOMA,
    MAX(SALARIO),
    MIN(SALARIO)
FROM
	DEPARTAMENTO
    INNER JOIN FUNCIONARIO ON
    DEPARTAMENTO.IDDEPARTAMENTO = FUNCIONARIO.IDFUNCIONARIO
    INNER JOIN FUNCAO ON
    FUNCIONARIO.IDFUNCIONARIO = FUNCAO.IDFUNCAO
GROUP BY 
	FUNCAO.NOME;